spring.application.name=my-portfolio

# DB接続設定
spring.datasource.url=jdbc:mysql://localhost:8889/my_portfolio?useSSL=false&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf設定
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# ファイルアップロード上限
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# サーバーポート
server.port=8080

# ファイルアップロード設定
file.upload.dir=${user.home}/Downloads/my-portfolio/src/main/resources/static/uploads